# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Jolene Branch
# Description of the Site
description: (in progress) Portfolio of Projects
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://github.com/jobranch2019/jobranch2019.github.io/blob/master/assets/images/red%20lightning.jpg
# heroimage: https://images.unsplash.com/photo-1623283596941-754adbf65a2c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MjU1fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60
# heroimage: https://images.unsplash.com/photo-1551272744-dc08dd02f2c5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTg5fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: jobranch@my365.bellevue.edu
facebook_username: //jolene.branch.9
instagram_username: jolene.branch
linkedin_username: jolene-branch-931a171b2
github_username:  jobranch2019

# Name of the Author
author-name: Jolene Branch
# URL for the Image of the Author
# (not supposed to include picture with resume with government jobs)
author-image: https://avatars.githubusercontent.com/u/51515313?v=4  
# 60 Words About the Author
author-about: I have a BS in Nursing from Viterbo University and a MS in Data Science from Bellevue University.  I worked as a staff nurse at the Mayo Clinic for the first nine years of my career and have been with the Department of Veterans Affairs since then. And yes, I have watched the Northern Lights dance from my home!
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/jobranch2019

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
#permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
